### ISSUE TITLE
Server URL gets truncated in links to attachments

### ISSUE THREAD

**Issue by taxnuke** [jk1/youtrack-idea-plugin#157]
Given server URL in settings: `https://track.123456789ab.ru`, URLs to attachments are of the following shape
`https://track.12345/api/files/...`. Which is clearly a truncation bug, this way every attachment link in issues is broken.

**Versions**
YouTrack Integration: 1.1.2
YouTrack: Build 2020.5.999 Tue, Nov 17, 2020, 11:18:52 AM UTC

WebStorm 2020.3.1
Build #WS-203.6682.155, built on December 28, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Key Promoter X, com.github.jk1.ytplugin, de.netnexus.camelcaseplugin

**Comment by lesslyrics** [comment]
Fixed, expected to be released in 1.1.5

**Comment by lesslyrics** [comment]
It is now released in 1.1.5, please feel free to reopen the issue if it occurs again.

**Comment by sergyu91ma** [comment]
Still happening. 

![image](https://user-images.githubusercontent.com/6949205/112727325-bac80080-8f2a-11eb-82ee-5b99f6cfecff.png)
